location __PATH__/ {
    alias __INSTALL_DIR__/;

    # Use PHP-FPM
    index index.php;

    try_files $uri $uri/ __PATH__/index.php?$query_string;

    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__NAME__.sock;

        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param REMOTE_USER $remote_user;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param SCRIPT_FILENAME $request_filename;
    }

    # Static assets with CORS headers for LHC widget
    location ~* \.(gif|jpe?g?|png|bmp|swf|css|js|svg|otf|eot|ttf|woff|woff2|mp3|ogg|wasm|map|wav|pdf|ico|txt)$ {
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS, PUT, DELETE";
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, API-Key, Authorization";
        expires 1M;
        access_log off;
    }

    # WASM MIME type
    types {
        application/wasm wasm;
    }
}
