; Start a new pool named '__NAME__'.
[__NAME__]

; Unix user/group of processes
user = __APP__
group = www-data

; The address on which to accept FastCGI requests.
listen = /var/run/php/php__PHP_VERSION__-fpm-__NAME__.sock

; Set listen(2) backlog. A value of '-1' means unlimited.
listen.backlog = 128

; Set permissions for unix socket
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500

; Pass environment variables
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/bin
env[TMP] = /tmp
env[TMPDIR] = /tmp
env[TEMP] = /tmp

; PHP settings
php_admin_value[upload_max_filesize] = 50M
php_admin_value[post_max_size] = 50M
php_admin_value[memory_limit] = 128M
php_admin_value[max_execution_time] = 300
php_admin_value[error_log] = /var/log/php/php__PHP_VERSION__-fpm-__NAME__.log
php_admin_flag[log_errors] = on

; Timezone
php_admin_value[date.timezone] = UTC
