#!/bin/bash

set -u
source _common.sh
source /usr/share/yunohost/helpers
ynh_abort_if_errors

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================
ynh_script_progression "Backing up the app main directory..."

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Backing up NGINX web server configuration..."

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# BACKUP THE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Backing up PHP-FPM configuration..."

ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"

#=================================================
# BACKUP THE MYSQL DATABASE
#=================================================
ynh_script_progression "Backing up the MySQL database..."

ynh_mysql_dump_db > db.sql

#=================================================
# BACKUP CRON JOB
#=================================================
ynh_backup "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
