#!/bin/bash

set -u
source _common.sh
source /usr/share/yunohost/helpers
ynh_abort_if_errors

#=================================================
# REMOVE CRON JOB
#=================================================
ynh_script_progression "Removing cron job..."

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
