#!/bin/bash

set -u
source _common.sh
source /usr/share/yunohost/helpers
ynh_abort_if_errors

#=================================================
# REMOVE CRON JOB
#=================================================
ynh_script_progression "Removing cron job..."

ynh_safe_rm "/etc/cron.d/$app"

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Removing PHP-FPM configuration..."

ynh_config_remove --template="$app" --destination="/etc/php/$php_version/fpm/pool.d/$app.conf"
ynh_systemctl --service="php${php_version}-fpm" --action=reload || true

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX configuration..."

ynh_config_remove --template="$app" --destination="/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_systemctl --service=nginx --action=reload || true

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
